### ISSUE TITLE
Mapwatch doesn't read the client file correctly when using Thaumaturgical hideout

### ISSUE THREAD

**Issue by akatosh100** [mapwatch/mapwatch#106]
It see's me going in and out of maps and my hideout, but doesn't record that I've done a map when finished. It does the same thing for all the maps I've tried. The problem corrected itself when I switched to another hideout. Is there any way I could edit the program myself to add my hideout and potentially future hideouts?

**Comment by erosson** [comment]
I never got around to exporting Harvest league data for Mapwatch; oops. Just did so, and it should fix this. (Should also fix map regions.) Please reopen if this is still broken!
