### ISSUE TITLE
Scratchpad/Checklist?

### ISSUE THREAD

**Issue by livejamie** [mapwatch/mapwatch#113]
It's nice to have Mapwatch sitting as a companion on my desktop, I'd love to have a small section that I could jot down notes, bonus points if I could do checklists or stuff in Markdown. 

This could be used to keep track of map trials, or write down certain drops, things to remember, etc.

**Comment by erosson** [comment]
I'm hesitant to add this. Easy enough to implement, and PoE note-taking has value, but:

* It actually makes maintenance more painful. Mapwatch currently has no persistent data that matters - just speech volume - and this would change that. I'd have to start being careful not to accidentally delete anyone's notes.
* I don't see what value it adds compared to the alternative I use now: a browser tab with keep.google.com, or some other note-taking app. Is there value to integrating this with map-watching that I'm not seeing?

**Comment by livejamie** [comment]
Ah if it's difficult to maintain then I understand.

I can keep another program open next to it, I just thought having a "one stop shop" would be nice. :)

**Comment by erosson** [comment]
Makes sense. I just don't want to risk accidentally nuking anyone's notes. Thanks for understanding!
