### ISSUE TITLE
Client.txt location settings

### ISSUE THREAD

**Issue by qqwtt** [mapwatch/mapwatch#131]
I think it would be wonderful it you could set the client.txt file location and save that to a config.
The thing is I have 2 installations of PoE (Steam&Standalone), and it takes the log file from the client that I launch once a year maybe.

**Comment by erosson** [comment]
Huh, could've sworn I was already storing the last manually-selected location, but it looks like I never got around to it. Oops! Will get to this soon, thanks.

https://github.com/mapwatch/mapwatch/blob/master/packages/electron2/src/electronBackend.js

**Comment by erosson** [comment]
Took longer than I expected to find time for this one; thanks for waiting! It should remember the last manually-selected path after I push v1.0.4 in a few minutes.
