### ISSUE TITLE
3.13 updates

### ISSUE THREAD

**Issue by erosson** [mapwatch/mapwatch#167]
* [x] envoy encounters ([Audio/Dialogue/NPC/Envoy/*](https://oriath.net/Endgame/Echoes/Envoy/) - no need for npctext, just speaker)
* [x] maven encounters (implies envoy, but envoy doesn't necessarily imply maven) ([Audio/Dialogue/NPC/Maven/*](https://oriath.net/Endgame/Echoes/Maven/) - no need for npctext, just speaker)
* [x] harvest encounters: oshabi voiceline (does this work after heart of the grove? does this work consistently?) ([Audio/Dialogue/NPC/Oshabi/OshabiWhenHarvesting*|OshabiWhenFightEnds*](https://oriath.net/League/Harvest/Oshabi/))
* [x] harvest: heart of the grove ([Audio/Dialogue/NPC/OshabiBoss/HarvestBossIntro*](https://oriath.net/League/Harvest/Oshabi/))
* [x] new area: the maven's crucible

sadly, rituals are not logged

**Comment by jozef-mitro** [comment]
For the encounters breakdown,  would it be possible to separate harvest instances within Zana maps and "natural" harvest instances? A lot of people are using Zana missions to target farm harvests and it would be handy to know statistics for just the "natural" harvests.

**Comment by erosson** [comment]
> For the encounters breakdown, would it be possible to separate harvest instances within Zana maps and "natural" harvest instances? A lot of people are using Zana missions to target farm harvests and it would be handy to know statistics for just the "natural" harvests.

Good idea, split it into a new issue, #179. There's no special tech for harvest - or 3.13 - there, it's just as easy to record the source for any side area.
