### ISSUE TITLE
loot tracking

### ISSUE THREAD

**Issue by erosson** [mapwatch/mapwatch#2]
> Can you write it so that when it parses the client text and notices that you enter your hideout (from a map) it does an inventory API pull request and then parse the json to get an output of how much currency (and other items) you looted during that run?

I'm personally interested in something like this for building a tool to track atlas progress - maps found, but not completed, is an important state to keep track of.

(I don't personally care much about tracking other kinds of loot though)

This would probably need a downloadable app instead of a webpage, for authentication.

https://www.reddit.com/r/pathofexile/comments/8lnctd/mapwatch_a_new_tool_to_automatically_time_your/dzgzl2j/

**Comment by lawrenz1337** [comment]
I can assure you that you will not need a downloadable app because you can use PHPSESSID from pathofexile.com and it will work! ;)

**Comment by erosson** [comment]
Unless I'm mistaken, I can't see pathofexile.com's PHPSESSID from a non-pathofexile.com browser tab. This thread tries to explain why: https://www.reddit.com/r/pathofexile/comments/8lnctd/mapwatch_a_new_tool_to_automatically_time_your/dzhfamo/?context=10000

**Comment by lawrenz1337** [comment]
Of course you can't  see it because it is a cross origin request. But you can give people an input for their PHPSESSID which they can take from poe website. You can see and example in Looty extension for chrome. If you want a collaborator for your tool I will gladly help btw cause I am a web dev myself. should I start with a PR of this feature?

**Comment by erosson** [comment]
It's still a cross-origin request even if you have the phpsessid though, isn't it? Cross-origin rules don't apply to extensions the same way as websites. Or do they set the right headers to allow those api calls from other websites, if you're authed?

I'm not really sure of the best way to implement loot tracking yet. Big task, I'm open to pull requests but it definitely needs discussion first!

Not even sure loot tracking's a good fit for mapwatch itself yet. If map-run start/end notifications could instead be turned into a library (#13), other tools that are already good at tracking loot like looty/currencycop/path of maps/etc. could use it to trigger their tracking around map-runs.

**Comment by lawrenz1337** [comment]
@erosson I forked your repo, and everything is fine except that I have never worked with elm before. Do you have a discord/skype or smth like that?

**Comment by erosson** [comment]
skype: erosson (I'll edit this line out soon for privacy's sake)

Could also try Reddit's chat, http://reddit.com/u/kawaritai - haven't actually tried it yet, but I pay more attention to Reddit than Skype, so odds are good

I usually ignore all messages while coding until I reach a break, so expect slow responses. Sorry in advance.

I documented the development process a bit (and just changed/fixed a bunch of it, so you should git-pull). It may help you get started: https://github.com/mapwatch/mapwatch/blob/master/CONTRIBUTING.md

Thanks for the interest!

**Comment by lawrenz1337** [comment]
@erosson Sorry I can't find you on skype :( Maybe we could try the other way around? My skype is darkwish007

**Comment by erosson** [comment]
And I can't find you on Skype. Weird. Discord: pierce#6074

**Comment by erosson** [comment]
another loot-tracking tool - designed for parties, but I'll bet it works solo too: https://www.reddit.com/r/pathofexile/comments/8w9ilc/release_exileparty_040b/

---

The more I think about it, the less I think loot tracking is a good fit for mapwatch itself. other tools already track loot very well, doesn't make sense to redo that work in mapwatch; and on top of that, I don't personally care about loot tracking enough to build or maintain it. instead, #13 will let developers of those tools integrate mapwatch to group loot by map-run.
