### ISSUE TITLE
Temple level estimate

### ISSUE THREAD

**Issue by aggixx** [mapwatch/mapwatch#22]
Would be pretty cool if Mapwatch could estimate the current level of the temple you're building based on the maps you've run since the last temple you ran (assuming you did an incursion in each one). I guess the user would have to tell it which maps they have shaped for it to know zone levels, but that isn't too hard to do I think.

**Comment by erosson** [comment]
Did anyone ever figure out the exact formula for temple level? Last I heard, people were thinking it was something like `min(highest-incursion-zone, (average-of-all-incursion-zones + some-constant))`, but I never heard if anyone figured out what the constant was.

> assuming you did an incursion in each one

No need to assume - Alva's "good job" line is logged, so the tool can know exactly what zones an incursion's done in.

> I guess the user would have to tell it which maps they have shaped for it to know zone levels, but that isn't too hard to do I think.

Shaped maps are actually one of the trickier parts of this. Can't just ignore them like I've done so far, they're too important for temple level. Nothing insurmountable, no suggestions needed, but there's more going on than you'd expect:

* What kind of UI for saying which maps are shaped?
  * a simple text field is tedious for users, begging for typos, and just feels shoddy
  * a list of all maps with checkboxes takes up a ton of space
  * fancy collapsible lists or autocompletion are nicer, but much harder to implement, and - depending which I chose - might still take up space on the page
  * pasting a screenshot of the atlas would be nice - takes up no room in the UI, should be pretty easy for the user (open atlas, print-screen, alt-tab, ctrl-v) - but very difficult to implement
* the best place to put this new UI isn't obvious. front page, before uploading the logfile? a separate preferences page? top of the history/maps/overview pages?
* if we know about shaped maps, there's other parts of the UI that should change when a map's shaped. map icons, tier/level in the maps and history pages, map name.
  * what about past runs, when a map might not have been shaped? - probably not important enough to worry about

**Comment by erosson** [comment]
Incursion's ended. Closing this for now, but worth reopening once we get [core incursion](https://www.pathofexile.com/forum/view-thread/2197247).
