### ISSUE TITLE
Obnoxious red text - missing Trialmaster mod?

### ISSUE THREAD

**Issue by remd** [mapwatch/mapwatch#235]
**TrialmasterChallengeChoiceMadeLessAOELessProjSpeedRandom TrialmasterChallengeChoiceMadeTwoTypesApplyRuinRandom**

Sorry for the giant screenshot:
![redtext](https://user-images.githubusercontent.com/1325809/115466857-a7911380-a1fe-11eb-9f15-89e7629cb1e7.png)

This is on v1.0.4.

**Comment by remd** [comment]
https://pastebin.com/z9YAc2vj - Client.txt content during that map.

**Comment by erosson** [comment]
Thanks for the report! This'll be fixed shortly.

**Comment by remd** [comment]
Thanks for the quick fix! I really appreciate all your continued hard work on this tool. ❤️
