### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by Rottenbeer** [mapwatch/mapwatch#244]
The app and the website don't load for me, are they down?

**Comment by erosson** [comment]
sure looks that way, investigating now

**Comment by erosson** [comment]
`erosson closed this` above was a misclick

site's back now. re-running the build process seems to have fixed this. my best guess is that two builds were triggered right next to each other, and their deployment steps must have tripped over each other. Created #245 to prevent this from reoccuring.

Thank you for reporting this!
