### ISSUE TITLE
Add option to cache Client.txt path in browser local storage

### ISSUE THREAD

**Issue by cozos** [mapwatch/mapwatch#26]
Hi there,

I love this tool for mapping, so thanks for all your hard work on it. I was thinking that it'd be nice QoL feature to let the user cache the path of their `Client.txt` in the browser's local storage. When you open the website, it will check if an existing `Client.txt` path exists in localStorage, and automatically load it. 

Let me know if you think this is a good idea. I wouldn't mind trying to help out with this.

**Comment by erosson** [comment]
Hi, glad you're enjoying Mapwatch!

This would be nice, but [unfortunately isn't possible](https://stackoverflow.com/questions/3582671/how-to-open-a-local-disk-file-with-javascript). A webpage can't open any local files, even if it knows the path, *unless the user manually selects the file*. My understanding is that it's a security thing, so random webpages can't go snooping around your hard drive.

I'm working on a downloadable version of mapwatch (#11) - downloadable/executable apps don't have the same restrictions, so it'll work exactly as you describe. Impossible in the browser version though.
