### ISSUE TITLE
[Suggestion] Uber Lab

### ISSUE THREAD

**Issue by thebeast792** [mapwatch/mapwatch#29]
Would be nice to have mapwatch time your labs and count how many you've run. Maybe even how many keys on average?

**Comment by erosson** [comment]
I'm open to adding this if people want it, but livesplit already does it: https://github.com/mapwatch/mapwatch#does-this-track-the-labyrinth-or-acts-1-10 , https://github.com/brandondong/POE-LiveSplit-Component

I've never tried it - uberlab runs aren't my thing - but it works as advertised for acts 1-10

> Maybe even how many keys on average?

not possible, poe's logfiles don't have anything that can be used to track this (or loot/items in general).

izaro's voice lines *are* logged, but counting darkshrines or tracking argus doesn't seem like it has much practical value

**Comment by erosson** [comment]
closing - haven't heard much demand for this, and livesplit still works.
