### ISSUE TITLE
Abyss broken image

### ISSUE THREAD

**Issue by tombomb** [mapwatch/mapwatch#343]
The abyssal depths image is dead

![image](https://user-images.githubusercontent.com/544509/152033146-043a722d-eef8-4926-ba1f-e24e93807ea2.png)

from the console its

https://web.poecdn.com/image/Art/2DArt/UIImages/InGame/Metamorphosis/rewardsymbols/ChestUnopenedAbyss.png?scale=1

my guess is its from here https://github.com/mapwatch/mapwatch/blob/master/packages/www/src/View/Icon.elm#L117 but I'm not 100%

**Comment by erosson** [comment]
This should be fixed shortly; thank you for reporting!
