### ISSUE TITLE
New hideouts seems not to be recognized

### ISSUE THREAD

**Issue by Sklifan** [mapwatch/mapwatch#39]
Greetings,

Tested the current version with 2 hideouts:
1) Skeletal Hideout (new one) doesn't start/end the time counter
2) Enlightened Hideout works fine

Would you please take a look into this?

Thanks!

Best regards

**Comment by erosson** [comment]
I fixed this pretty early on in the league, and it works for me now (though I neglected to add it to the changes page): 4a10aa5114675acb50b07337c6ae4a8d95df27fc

What's the latest date you see on the changes page? Could you try clearing your browser cache to be sure you're seeing the latest version? Thanks; sorry for the trouble.

**Comment by Sklifan** [comment]
Cool, works fine for me.

Many thanks for the quick response!
