### ISSUE TITLE
secret hideouts

### ISSUE THREAD

**Issue by erosson** [mapwatch/mapwatch#40]
#39 related - 4a10aa5114675acb50b07337c6ae4a8d95df27fc added hideouts from the in-game list, but apparently that's not a complete list! [reddit](https://www.reddit.com/r/pathofexile/comments/a63on0/it_took_about_100_icebergs_but_i_was_rewarded/) talked about a glacial hideout in a map, didn't sound familiar.

https://poedb.tw/us/Hideouts - glacial, arboreal, brutal, overgrown, robber's trench, sunken

can we just do a regex for ".* hideout"? - no, because the syndicate has non-town hideouts

**Comment by He3F** [comment]
Can confirm that there is a Glacial Hideout, as i own it. It and some other zone is currently preventing mapwatch of tracking maps. 

If i go into client.txt and change
2018/12/13 19:43:48 1553883296 a24 [INFO Client 25376] : You have entered Glacial Hideout.
to something like this
2018/12/13 19:43:48 1553883296 a24 [INFO Client 25376] %<WTFF> ThirstyForTheSouls: Be Gone!

Then MapWatch is able to track abit more maps, untill it meets yet an other hideout that is not in the list.
