### ISSUE TITLE
Rituals no longer being logged

### ISSUE THREAD

**Issue by ruhhh** [mapwatch/mapwatch#435]
It seems that as of the latest patch (3.20.1) Rituals are no longer being logged and therefore not able to be tracked.
If I understand correctly the log file is checked for "FindClosestObject found no nearby object".
This line is no longer logged when you encounter/click on a Ritual.

I guess there is nothing you can do about it if it's not logged anymore, but I thought I should at least inform you.

**Comment by erosson** [comment]
Thanks for letting me know. You're right, `FindClosestObject` is how ritual logs work, so removing that breaks ritual logging. Too bad.

Code will eventually be removed in #399
