### ISSUE TITLE
Chinese can't work

### ISSUE THREAD

**Issue by 14776302** [mapwatch/mapwatch#45]
Map: https://docs.google.com/spreadsheets/d/1zakVv3EO4xIKJCP2ZlU2KE_kTg-tt1kgx3X5vO5E-24/edit?usp=sharing
Client: https://drive.google.com/file/d/1K91X9D437t1pUW1QcD-1gN7yKHiINbpG/view?usp=sharing

**Comment by erosson** [comment]
Thank you for the updated names! Sorry for the long wait before I could fix this! I think it will work now.
