### ISSUE TITLE
Make all columns sortable on all tabs

### ISSUE THREAD

**Issue by jnitis** [mapwatch/mapwatch#46]
Feature request, thank you!

**Comment by erosson** [comment]
Implemented for the maps page! I've thought this would be handy there too.

Does this make sense for the history page? Some of the columns have multiple values so the UI's tricky, and I'm not sure why/how it'd be useful - feels like the page is fundamentally chronological to me. Feel free to create a new issue or reopen if you have a use for this, and I might reconsider!
