### ISSUE TITLE
Blank screen after launching an application

### ISSUE THREAD

**Issue by Fiesta9** [mapwatch/mapwatch#498]
Hi guys, for about a month the program has been working great. But lately it starts up and the program screen is just blank and nothing is displayed. I have reinstalled it several times but it doesn't help. Please help me
https://imgur.com/MxUdWD4

**Comment by Shellcarnage** [comment]
I am also experiencing the same issue, I installed yesterday and had no problems, restarted PC and now suffering with same black blank screen as screenshotted

**Comment by erosson** [comment]
I updated Mapwatch just yesterday (ancestor league stuff), so the timing tells me the update probably broke something for you all. It still works fine for me though, which means I can't see what's wrong.

If you see a blank screen when starting the app: please press `ctrl + shift + i`, then the `console` button at the top of the screen. It'll probably show you an error message, a bit like the one below - screenshot or copy that error here. That'll give me what I need to start fixing this. Thanks, and sorry for the trouble!
![image](https://github.com/mapwatch/mapwatch/assets/238846/94b8cca5-6839-4d5e-8a4d-a276555fda9c)

**Comment by erosson** [comment]
bdd1e2c should fix this for future updates. Cause: mapwatch was caching things wrong, both in the browser and in the cdn, so any update could cause this problem temporarily.

If you're still seeing this, try pressing `ctrl + F5`. (The most recent fix should make this unnecessary for future updates, but might still be necessary now.) If that doesn't work, tell me if https://mapwatch.erosson.org broken too, or just the app?

**Comment by mourgne** [comment]
Pressing ctrl + F5 does not resolve the issue for me. I see the same failure to load resource that is seen in the screenshot.  

When I upload my client.txt to https://mapwatch.erosson.org/, it successfully parses the file and I can see my mapping history and current map.

**Comment by Shellcarnage** [comment]
> 

Opening the console and pushing Ctrl + F5 has fixed the app for me, thank you
