### ISSUE TITLE
implement chrome native filesystem api; can we avoid permissions errors?

### ISSUE THREAD

**Issue by erosson** [mapwatch/mapwatch#51]
try to use the official replacement for our file-watching hackery. does it work at all? can we poll files? if it fails, get electron working or figure out something else. 

to get started, it's `window.chooseFileSystemEntries()`

* intro: https://web.dev/native-file-system/
* spec: https://wicg.github.io/native-file-system/

---

unfortunately, I've already run into problems while trying this out :(

* enable chrome://flags/#native-file-system-api and restart
* open js console
* `window.chooseFileSystemEntries()` > choose client.txt

![image](https://user-images.githubusercontent.com/238846/71852113-fb2d2b80-30a5-11ea-84aa-79270a63b81f.png)

is there anything we can do about this? if not, probably need to promote the electron version. sigh.

**Comment by erosson** [comment]
Zana: I have some good news and some bad news. The good news is that [a hard link](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink) to client.txt from a safer directory works perfectly - no security errors, and log-polling works. The bad news is that [creating a symlink requires either administrator powers or developer mode](https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/).

So, assuming the security restrictions I'm seeing for the new API don't change, we have two choices:

* promote the electron app, kill the website
* create a launcher/setup-program that creates the symlink, with manual setup steps for the security-conscious

I like that the symlink approach would keep things mostly-webapp, minimizing access to the user's machine, and need infrequent updates - but the minimal access it needs has an admin prompt. the admin requirement locks out many users; and more importantly, training users to accept admin prompts from random apps like mine is bad. electron's probably the right choice, unfortunately.

---

snapshotting test, from js console: 

    var file=null; window.chooseFileSystemEntries().then(f => {file=f})
    /* choose the client.txt file. open poe. run the line below a few times while playing; see that it changes. */
    file.getFile().then(f => f.text()).then(text => console.log(text.length))

**Comment by erosson** [comment]
Turns out that creating a hard link doesn't need admin permissions! I assumed too much after trying out things above with symlinks. The second solution above (one-time launcher) doesn't need an admin prompt after all, and now looks much more appealing!

**Comment by erosson** [comment]
I'm promoting the electron version. The only way to avoid a download and keep file-watching is to instruct people to hardlink the log file, which is unacceptable. (I could script the hardlinking, but users need to download/run the script, which defeats the purpose.)

I'll still implement this - it'll be an option for power users who don't trust my download, with instructions for creating the hard link. (It'll also be useful if GGG ever moves the logfile into a safer folder, though that's unlikely - Chris has said he's not crazy about third-party tools.)

**Comment by erosson** [comment]
The magic hardlink-creation line we'll be sharing with users:

`mklink /H "C:\Users\%USERNAME%\Documents\My Games\Path of Exile\mapwatch.erosson.org---Client.txt" "C:\Program Files (x86)\Grinding Gear Games\Path of Exile\logs\Client.txt"`

**Comment by erosson** [comment]
Electron vs. nativefs-and-command-prompt has some security implications. My thought process on that is below.

---

**Why go to the trouble of implementing `nativefs` at all, when I could solely promote the Electron version?**

Because I think it's *awful* that PoE players have to rely on so many dangerous third-party executables. Browser-based tools are safer. I hate adding one more dangerous executable to the mix - but for non-technical users, removing Mapwatch's most important feature is my only other choice.

The best I can do is give technical/security-conscious folks a safer alternative.

I guess I could also lobby for Chrome to change their rules, or GGG to move `client.txt` to another directory. Those are both incredibly unlikely to happen; Mapwatch isn't big enough.

**"Run this code in your command prompt, I promise it's safe, really" is no better than downloading dangerous executables.**

True! Running random shell code can be dangerous. You shouldn't do it if you don't understand the code you're running.

In this case, the code I'm recommending is one short, relatively-readable line with no downloads/imports. Technical folks can see what it does, see that it's safe, and avoid installing one more dangerous executable.

**You might be accidentally teaching non-technical folks that it's safe to run code in the command prompt. It's not, and that's dangerous.**

Also true! It's not okay to run code from strangers in the (dangerous) command prompt if you don't have the skill to understand what you're running. I'm *deliberately* not telling users how to open a command prompt, because I don't want them to think it's normal/okay unless they know what they're doing.

It's also not okay to run executables from strangers - but that risk has been publicized much better. Non-technical users are more likely to already understand "this strange executable might be dangerous, but I'm okay with that risk" than they are to understand "this command-prompt thingy might be dangerous".

**Instead of command prompt instructions, why not offer a batch file or some sort of launcher program?**

That's just another kind of executable to download, which is no better for security. Command prompt instructions force technical folks to see what's going on, allowing them to limit their exposure to the dangerous stuff.

**Comment by valen214** [comment]
I really like the idea of moving stuff up to the web so as to protect the user, through encapsulating everything under the browser, which should do a better job at security than self-written third party programs.

I think you should add an entry to [releases](https://github.com/mapwatch/mapwatch/releases) or the readme.
It took me a while to discover this and I'm sure 99% of users don't even notice this awesome feature/webapp
