### ISSUE TITLE
Appears to be broken in Chrome - no data

### ISSUE THREAD

**Issue by Turinqui** [mapwatch/mapwatch#52]
No maps are being picked up - my log is attached
[Client.txt](https://github.com/mapwatch/mapwatch/files/4038752/Client.txt)
https://i.imgur.com/XocSCLv.png

**Comment by erosson** [comment]
Any luck now? Your log works for me, but I can confirm it didn't work for me earlier.

I pushed an update (unrelated) a few minutes ago, and something in there seems to have fixed things for me - though I'm not sure what was going wrong before.

**Comment by Turinqui** [comment]
Yep, all fixed, thanks!
