### ISSUE TITLE
shut down mapwatch

### ISSUE THREAD

**Issue by erosson** [mapwatch/mapwatch#557]
mapwatch is such a great idea that GGG copied it to the core game, as the timekeeper's map device! (I have no idea if mapwatch actually had anything to do with it, but it's nice to imagine it did.)

Once it's available in the store/not just in mystery boxes, I see no reason to maintain mapwatch's timer anymore. This is pretty huge, because [the timer is the reason why the downloadable version of mapwatch exists](https://github.com/mapwatch/mapwatch/blob/master/WATCHING.md)! Without it, there's little reason to ask users to download an executable - so I can stop maintaining not just the timer page, but the entire downloadable app in `electron2`.

Need to add a new message visible only to existing app users, telling them about the removal and sending them to the website. 

timekeeper's not actually in the store yet, but it's likely to appear one month after league start, around Jan 8. Don't release this change before then. 

---

Some users probably prefer the app's UI, and will complain that it's gone. I do not care, at all. The PoE community needs fewer third-party downloads, encouraging people to download apps makes the whole ecosystem more dangerous, and I'm happy to stop being a part of that. Also, less maintenance work for me.

Some users might prefer mapwatch over the timekeeper's map device because it's free. But maintaining it isn't free for me - not worth it when there's an alternative. Also, mapwatch's event tracking/history is way more popular than its realtime stuff these days - unlikely to really see many complaints.

---

the timer is why I created mapwatch in the first place, and a big motivator for continuing to maintain it. is it still worth maintaining mapwatch at all anymore? 

**yes**, I think - its history tracking/map counting is still pretty useful and popular. (I saw steelmage use it to count a specific map on stream yesterday, in front of thousands of viewers!) I am less interested in that part these days though, even if it is more popular, so let's wait and see how I feel about things a few months after removing realtime stuff.

**Comment by ganego** [comment]
Before you remove anything, how about you release it first?  
The latest release is from three years ago(?)

What good is this tool when it's completely outdated?

**Comment by erosson** [comment]
> The latest release is from three years ago

It's been up to date - in both the website and the app, you'll see a "hide pre-Affliction" maps button that proves it. 

Mapwatch has two formats: this download and the website. The download's connected to the Mapwatch web site, which is updated [much more often](https://github.com/mapwatch/mapwatch/commits/master/). Updates that change the download's version and release date are rarely necessary. 

I hope that makes sense? I can see how the release date's confusing though, sorry - updated the download's description with an explanation.

**Comment by erosson** [comment]
timekeeper's map device has launched, this is now unblocked: https://www.pathofexile.com/shop/item/TimekeepersMapDeviceVariations

(oof, $27 is steep. still not worth continuing to maintain this though)

**Comment by erosson** [comment]
> the timer is why I created mapwatch in the first place, and a big motivator for continuing to maintain it. is it still worth maintaining mapwatch at all anymore?
> 
> **yes**, I think ...

I've thought about this over the past few months. **No**, now that the timer's obsolete, maintaining Mapwatch isn't worth it to me anymore. Even if the history features are still used, I'm just not personally interested in them these days. Will be closing things down shortly.

**Comment by remd** [comment]
@erosson Is it reasonable to archive the repo at this point?
