### ISSUE TITLE
Some maps are not parsed in the log

### ISSUE THREAD

**Issue by manygrou** [mapwatch/mapwatch#66]
When i use https://mapwatch.erosson.org/#/history to parse my log, some maps do not show.
Here is an extract of my actual log, it's missing at least one Plateau map with Drox second taunt (2020/02/02 19:38:58) and the Desert map with Drox actual fight (2020/02/03 08:33:01).

[Client.txt](https://github.com/mapwatch/mapwatch/files/4149104/Client.txt)

**Comment by erosson** [comment]
Thanks for the report! It looks like, in both of these maps, you went offline (as in, exited the game for more than 30 minutes) without going back to town first - is that right? 

When this happens, it's not possible to tell when you finished the map - there's no "exited the game" timestamp in the log file, so an accurate end time for those maps simply isn't possible. Mapwatch's current behavior is to simply ignore maps with no ending timestamp, which was reasonable behavior until recently. It interacts pretty badly with conqueror tracking though, doesn't it? Might be better to include unknown-duration-maps in the history with a "??:??" duration or something; I'll see what I can do about that soon.

Until I fix that, a workaround is to portal to town before logging out.

**Comment by manygrou** [comment]
Thanks for the reply! 
I was afk for a long time (eating) but i don't think i exited the game.
I'll port out to town in the future :)

**Comment by erosson** [comment]
This should be fixed - map runs with unknown durations are now visible.
