### ISSUE TITLE
Timing out in Simulacrum

### ISSUE THREAD

**Issue by remd** [mapwatch/mapwatch#68]
Mapwach was unable to track a Simulacrum (Oriath Delusion) that took approximately 30-35 minutes. Is there way to extend the timeout for Simulacrum, or in a general setting somewhere?

This was preceded by a Simulacrum on a different layout (The Bridge Enraptured) that Mapwatch was able to track (25:07 in map).

![simulacrum-timeout](https://user-images.githubusercontent.com/1325809/78085527-3aa7a300-7389-11ea-8bfd-2ec1eff54a53.png)

Thanks for your hard work on this tool.

**Comment by erosson** [comment]
Thanks for the report! Simulacrum definitely lasts long enough that the current half-hour timeout doesn't work well for it, you're right.

A nicer fix would be to reset the timeout whenever an npc says something - special-casing the simulacrum is much easier to implement though.

Simulacrum's the only map that lasts long enough for a longer timeout to make sense, so I'll keep the existing timeout for other maps.

**Comment by remd** [comment]
Thank you!
