### ISSUE TITLE
Feature Request: Make the electron App load the client.txt by default.

### ISSUE THREAD

**Issue by Leoguy77** [mapwatch/mapwatch#73]
As described in the title it would be useful to have the app select the client.txt by default cause there isnt really a point in selecting it by hand. just try the default locations and then ask for the file when the file couldnt be found

**Comment by erosson** [comment]
That's exactly what it's already trying to do, actually! If you see the same choose-file intro screen as the web version, autoloading failed.

[Is your client.txt in this list of paths we try to autoload](https://github.com/mapwatch/mapwatch/blob/20d4123ab31039a96d0d190d5a671fff1841b063/packages/electron2/src/electronBackend.js#L22)? If not, maybe I should add it - where is yours? If so, I'll search for other bugs - it works for me, but maybe something's wrong for others.

**Comment by Leoguy77** [comment]
I see the problem: you forgot the Steam paths. my path is "C:\Program Files (x86)\Steam\steamapps\common\Path of Exile\logs". you should also add "C:\Program Files\Steam\steamapps\common\Path of Exile\logs"

**Comment by erosson** [comment]
I have a steam path in there, but it looks like there's a few different possible steam paths that I missed. Fix will be released soon. Thanks for the report!

**Comment by Leoguy77** [comment]
thanks for the quick answers. keep up the good work :)

**Comment by erosson** [comment]
Released, thanks for waiting! It should auto-update after you restart it, or you can download it directly: https://github.com/mapwatch/mapwatch/releases/tag/v1.0.2
